spring.application.name=ERSBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/reimbursement2_copy
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Specify what DB schema we're pointing to
spring.jpa.properties.hibernate.default_schema=reimbursement_schema

# This will create a new schema if it doesn't exist already
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
